// Catalogue de marques automobiles proposé au dépôt d'annonce et au filtre
// Marque — fourni par Nicolas le 2026-08-22 sur le modèle d'un filtre de
// référence. Les "courantes" sont affichées en premier et dans cet ordre
// précis ; les "autres" en ordre alphabétique, avec "Autre" en dernier
// recours pour une marque absente de la liste.
export const MARQUES_COURANTES = [
  "AUDI",
  "BMW",
  "CITROEN",
  "FIAT",
  "FORD",
  "MERCEDES-BENZ",
  "MINI",
  "NISSAN",
  "OPEL",
  "PEUGEOT",
  "RENAULT",
  "TOYOTA",
  "VOLKSWAGEN",
] as const;

export const MARQUES_AUTRES = [
  "ABARTH",
  "AC",
  "ACURA",
  "AIWAYS",
  "AIXAM",
  "ALFA ROMEO",
  "ALPINA",
  "ALPINE",
  "ALVIS",
  "AMC",
  "ARIEL",
  "ARO",
  "ASTON MARTIN",
  "AUSTIN",
  "AUSTIN HEALEY",
  "AUTOBIANCHI",
  "AUVERLAND",
  "BEIJING",
  "BELLIER",
  "BENTLEY",
  "BERTONE",
  "BLUECAR",
  "BUGATTI",
  "BUICK",
  "BYD",
  "CADILLAC",
  "CASALINI",
  "CATERHAM",
  "CHATENET",
  "CHERY",
  "CHEVROLET",
  "CHRYSLER",
  "CUPRA",
  "DACIA",
  "DAEWOO",
  "DAF",
  "DAIHATSU",
  "DAIMLER",
  "DANGEL",
  "DATSUN",
  "DE LOREAN",
  "DE TOMASO",
  "DELAGE",
  "DELAHAYE",
  "DENZA",
  "DFSK",
  "DODGE",
  "DS",
  "ELARIS",
  "EXCALIBUR",
  "FACEL VEGA",
  "FERRARI",
  "FISKER",
  "FOTON",
  "GEELY",
  "GENERAL MOTORS",
  "GENESIS",
  "GURGEL",
  "HONDA",
  "HONGQI",
  "HOTCHKISS",
  "HUMMER",
  "HYUNDAI",
  "IMF",
  "INEOS",
  "INFINITI",
  "INNOCENTI",
  "ISUZU",
  "JAECOO",
  "JAGUAR",
  "JDM SIMPA",
  "JEEP",
  "JENSEN",
  "KIA",
  "KILOW",
  "KTM",
  "LADA",
  "LAMBORGHINI",
  "LANCIA",
  "LAND-ROVER",
  "LEAPMOTOR",
  "LEVC",
  "LEXUS",
  "LIGIER",
  "LINCOLN",
  "LOTUS",
  "LYNK&CO",
  "MAHINDRA",
  "MARCOS",
  "MASERATI",
  "MATRA",
  "MAYBACH",
  "MAZDA",
  "MCLAREN",
  "MEGA",
  "MERCURY",
  "MG/MG MOTOR",
  "MIA ELECTRIC",
  "MICROCAR",
  "MICRODRIVE",
  "MITSUBISHI",
  "MOBILIZE",
  "MORGAN",
  "MORRIS",
  "MPM",
  "NIO",
  "NSU",
  "OLDSMOBILE",
  "OMODA",
  "PANHARD",
  "PANTHER",
  "PGO",
  "PIAGGIO",
  "PLYMOUTH",
  "POLESTAR",
  "PONTIAC",
  "PORSCHE",
  "PROTON",
  "ROLLS-ROYCE",
  "ROVER",
  "SAAB",
  "SANTANA",
  "SEAT",
  "SERES",
  "SILENCE",
  "SIMCA",
  "SIMPLICI",
  "SKODA",
  "SKYWORTH",
  "SMART",
  "SSANGYONG",
  "STUDEBAKER",
  "SUBARU",
  "SUNBEAM",
  "SUZUKI",
  "TALBOT",
  "TESLA",
  "TRABANT",
  "TRIUMPH",
  "TVR",
  "UMM",
  "VENTURI",
  "VESPA",
  "VINFAST",
  "VOLVO",
  "XEV",
  "XPENG",
  "ZEEKR",
] as const;

// Catalogue complet, dans l'ordre d'affichage (courantes puis autres) — pas
// "AUTRE", qui reste une valeur de secours au dépôt, jamais une entrée du
// filtre (elle ne veut rien dire pour un acheteur qui filtre).
export const MARQUES_CATALOGUE: readonly string[] = [...MARQUES_COURANTES, ...MARQUES_AUTRES];
