// Catalogue de marques automobiles proposé au dépôt d'annonce et au filtre
// Marque — fourni par Nicolas (liste du 2026-08-22, remplace une première
// version). Les "courantes" sont affichées en premier et dans cet ordre
// précis ; les "autres" en ordre alphabétique, avec "Autre" en dernier
// recours pour une marque absente de la liste.
//
// "CITROEN" est volontairement sans tréma (la source de Nicolas écrit
// "Citroën") pour matcher les données déjà normalisées en base et la valeur
// déjà déployée du menu de dépôt — changer l'un sans l'autre casserait le
// filtre pour ces annonces.
export const MARQUES_COURANTES = [
  "AUDI",
  "BMW",
  "CITROEN",
  "FIAT",
  "FORD",
  "MERCEDES-BENZ",
  "MINI",
  "NISSAN",
  "OPEL",
  "PEUGEOT",
  "RENAULT",
  "TOYOTA",
  "VOLKSWAGEN",
] as const;

export const MARQUES_AUTRES = [
  "ABARTH",
  "AC",
  "AIXAM",
  "ALFA ROMEO",
  "ALPINA",
  "ALPINE",
  "ANAIG",
  "ARIEL",
  "ARO",
  "ARTEGA",
  "ASPP",
  "ASTON MARTIN",
  "AUSTIN",
  "AUSTIN HEALEY",
  "AUTOBIANCHI",
  "BELLIER",
  "BENTLEY",
  "BERTONE",
  "BLUECAR GROUPE BOLLORE",
  "BOLLORE",
  "BUGATTI",
  "BUICK",
  "BYD",
  "CADILLAC",
  "CARBODIES",
  "CARVER",
  "CASALINI",
  "CATERHAM",
  "CHATENET",
  "CHEVROLET",
  "CHRYSLER",
  "CUPRA",
  "DACIA",
  "DAEWOO",
  "DAIHATSU",
  "DAIMLER",
  "DALLARA",
  "DANGEL",
  "DATSUN",
  "DE TOMASO",
  "DEVINCI",
  "DFSK",
  "DODGE",
  "DONKERVOORT",
  "DS",
  "ECLASSIC CARS",
  "ESTRIMA",
  "EXCALIBUR",
  "FACEL VEGA",
  "FERRARI",
  "FISKER",
  "FOTON",
  "FSO",
  "GEELY",
  "GENESIS",
  "GMC",
  "GURGEL",
  "HONDA",
  "HOTCHKISS",
  "HUMMER",
  "HYUNDAI",
  "INEOS",
  "INFINITI",
  "INNOCENTI",
  "ISUZU",
  "IVECO",
  "JAECOO",
  "JAGUAR",
  "JANNARELLY",
  "JDM SIMPA",
  "JEEP",
  "JIAYUAN",
  "JINMA",
  "KATE",
  "KIA",
  "LADA",
  "LAMBORGHINI",
  "LANCIA",
  "LAND ROVER",
  "LEAPMOTOR",
  "LIGIER",
  "LINCOLN",
  "LOTUS",
  "LYNK & CO",
  "MAHINDRA",
  "MAN",
  "MARTIN",
  "MASERATI",
  "MATRA",
  "MAXUS",
  "MAYBACH",
  "MAZDA",
  "MCLAREN",
  "MEGA",
  "MERCEDES-AMG",
  "MERCURY",
  "MG",
  "MICRO",
  "MICROCAR",
  "MICRODRIVE",
  "MINAUTO",
  "MITSUBISHI",
  "MLT",
  "MOBILIZE",
  "MOKE",
  "MORGAN",
  "MORRIS",
  "MPM MOTORS",
  "NECKAR",
  "NOSMOKE",
  "OLDSMOBILE",
  "OMODA",
  "PAMBUFFETTI",
  "PANHARD",
  "PANTHER",
  "PGO",
  "PIAGGIO",
  "PLYMOUTH",
  "POLESTAR",
  "PONTIAC",
  "PORSCHE",
  "RAM",
  "ROLLS ROYCE",
  "ROVER",
  "SAAB",
  "SANTANA",
  "SEAT",
  "SECMA",
  "SERES",
  "SHELBY",
  "SILENCE",
  "SIMCA",
  "SIMPLICI",
  "SKODA",
  "SKYWORTH",
  "SMART",
  "SSANGYONG",
  "SUBARU",
  "SUZUKI",
  "TALBOT SIMCA",
  "TEILHOL",
  "TESLA",
  "TRABANT",
  "TRIUMPH",
  "TVR",
  "VESPA",
  "VOLVO",
  "WESTFIELD",
  "WIESMANN",
  "XPENG",
  "ZEEKR",
] as const;

// Catalogue complet, dans l'ordre d'affichage (courantes puis autres) — pas
// "AUTRE", qui reste une valeur de secours au dépôt, jamais une entrée du
// filtre (elle ne veut rien dire pour un acheteur qui filtre).
export const MARQUES_CATALOGUE: readonly string[] = [...MARQUES_COURANTES, ...MARQUES_AUTRES];
