// Catalogue de marques automobiles proposé au dépôt d'annonce et au filtre
// Marque — fourni par Nicolas (deux listes du 2026-08-22, fusionnées : rien
// n'est retiré de la première liste, la seconde ne fait qu'en compléter le
// contenu). Les "courantes" sont affichées en premier et dans cet ordre
// précis ; les "autres" en ordre alphabétique, avec "Autre" en dernier
// recours pour une marque absente de la liste.
//
// Quelques entrées se recoupent volontairement sans être fusionnées
// ("BLUECAR" / "BLUECAR GROUPE BOLLORE", "MG/MG MOTOR" / "MG", "MPM" / "MPM
// MOTORS", "LYNK&CO" / "LYNK & CO", "TALBOT" / "TALBOT SIMCA") : la consigne
// du 2026-08-22 est de ne rien retirer, pas de faire un choix éditorial entre
// deux formulations d'un même nom fourni par deux sources différentes.
//
// "CITROEN" est volontairement sans tréma (une des deux sources écrit
// "Citroën") pour matcher les données déjà normalisées en base et la valeur
// déjà déployée du menu de dépôt — changer l'un sans l'autre casserait le
// filtre pour ces annonces.
export const MARQUES_COURANTES = [
  "AUDI",
  "BMW",
  "CITROEN",
  "FIAT",
  "FORD",
  "MERCEDES-BENZ",
  "MINI",
  "NISSAN",
  "OPEL",
  "PEUGEOT",
  "RENAULT",
  "TOYOTA",
  "VOLKSWAGEN",
] as const;

export const MARQUES_AUTRES = [
  "ABARTH",
  "AC",
  "ACURA",
  "AIWAYS",
  "AIXAM",
  "ALFA ROMEO",
  "ALPINA",
  "ALPINE",
  "ALVIS",
  "AMC",
  "ANAIG",
  "ARIEL",
  "ARO",
  "ARTEGA",
  "ASPP",
  "ASTON MARTIN",
  "AUSTIN",
  "AUSTIN HEALEY",
  "AUTOBIANCHI",
  "AUVERLAND",
  "BEIJING",
  "BELLIER",
  "BENTLEY",
  "BERTONE",
  "BLUECAR",
  "BLUECAR GROUPE BOLLORE",
  "BOLLORE",
  "BUGATTI",
  "BUICK",
  "BYD",
  "CADILLAC",
  "CARBODIES",
  "CARVER",
  "CASALINI",
  "CATERHAM",
  "CHATENET",
  "CHERY",
  "CHEVROLET",
  "CHRYSLER",
  "CUPRA",
  "DACIA",
  "DAEWOO",
  "DAF",
  "DAIHATSU",
  "DAIMLER",
  "DALLARA",
  "DANGEL",
  "DATSUN",
  "DE LOREAN",
  "DE TOMASO",
  "DELAGE",
  "DELAHAYE",
  "DENZA",
  "DEVINCI",
  "DFSK",
  "DODGE",
  "DONKERVOORT",
  "DS",
  "ECLASSIC CARS",
  "ELARIS",
  "ESTRIMA",
  "EXCALIBUR",
  "FACEL VEGA",
  "FERRARI",
  "FISKER",
  "FOTON",
  "FSO",
  "GEELY",
  "GENERAL MOTORS",
  "GENESIS",
  "GMC",
  "GURGEL",
  "HONDA",
  "HONGQI",
  "HOTCHKISS",
  "HUMMER",
  "HYUNDAI",
  "IMF",
  "INEOS",
  "INFINITI",
  "INNOCENTI",
  "ISUZU",
  "IVECO",
  "JAECOO",
  "JAGUAR",
  "JANNARELLY",
  "JDM SIMPA",
  "JEEP",
  "JENSEN",
  "JIAYUAN",
  "JINMA",
  "KATE",
  "KIA",
  "KILOW",
  "KTM",
  "LADA",
  "LAMBORGHINI",
  "LANCIA",
  "LAND ROVER",
  "LEAPMOTOR",
  "LEVC",
  "LEXUS",
  "LIGIER",
  "LINCOLN",
  "LOTUS",
  "LYNK & CO",
  "LYNK&CO",
  "MAHINDRA",
  "MAN",
  "MARCOS",
  "MARTIN",
  "MASERATI",
  "MATRA",
  "MAXUS",
  "MAYBACH",
  "MAZDA",
  "MCLAREN",
  "MEGA",
  "MERCEDES AMG",
  "MERCURY",
  "MG",
  "MG/MG MOTOR",
  "MIA ELECTRIC",
  "MICRO",
  "MICROCAR",
  "MICRODRIVE",
  "MINAUTO",
  "MITSUBISHI",
  "MLT",
  "MOBILIZE",
  "MOKE",
  "MORGAN",
  "MORRIS",
  "MPM",
  "MPM MOTORS",
  "NECKAR",
  "NIO",
  "NOSMOKE",
  "NSU",
  "OLDSMOBILE",
  "OMODA",
  "PAMBUFFETTI",
  "PANHARD",
  "PANTHER",
  "PGO",
  "PIAGGIO",
  "PLYMOUTH",
  "POLESTAR",
  "PONTIAC",
  "PORSCHE",
  "PROTON",
  "RAM",
  "ROLLS ROYCE",
  "ROVER",
  "SAAB",
  "SANTANA",
  "SEAT",
  "SECMA",
  "SERES",
  "SHELBY",
  "SILENCE",
  "SIMCA",
  "SIMPLICI",
  "SKODA",
  "SKYWORTH",
  "SMART",
  "SSANGYONG",
  "STUDEBAKER",
  "SUBARU",
  "SUNBEAM",
  "SUZUKI",
  "TALBOT",
  "TALBOT SIMCA",
  "TEILHOL",
  "TESLA",
  "TRABANT",
  "TRIUMPH",
  "TVR",
  "UMM",
  "VENTURI",
  "VESPA",
  "VINFAST",
  "VOLVO",
  "WESTFIELD",
  "WIESMANN",
  "XEV",
  "XPENG",
  "ZEEKR",
] as const;

// Catalogue complet, dans l'ordre d'affichage (courantes puis autres) — pas
// "AUTRE", qui reste une valeur de secours au dépôt, jamais une entrée du
// filtre (elle ne veut rien dire pour un acheteur qui filtre).
export const MARQUES_CATALOGUE: readonly string[] = [...MARQUES_COURANTES, ...MARQUES_AUTRES];
